import { describe, expect, it } from 'vitest'
import { BotEngine } from './engine'
import { radiusAtAngle } from './shape'
import { EXPRESSION_BY_ID } from './expressions'
import { REST_GAZE } from './face'
import { SHAPE_BY_ID } from './skins'
import { SEQUENCE, STATES, type StateId } from './states'

/** Anchor points of a path generated by closedPath (control points are ignored). */
function anchors(d: string): Array<[number, number]> {
  const out: Array<[number, number]> = []
  const head = /^M(-?[\d.]+) (-?[\d.]+)/.exec(d)
  if (head) out.push([+head[1]!, +head[2]!])
  for (const seg of d.matchAll(/C[-\d. ]+? (-?[\d.]+) (-?[\d.]+)(?=C|Z)/g)) {
    out.push([+seg[1]!, +seg[2]!])
  }
  return out
}

function footprint(d: string) {
  const pts = anchors(d)
  const xs = pts.map((p) => p[0])
  const ys = pts.map((p) => p[1])
  return {
    w: (Math.max(...xs) - Math.min(...xs)) / 100,
    h: (Math.max(...ys) - Math.min(...ys)) / 100
  }
}

/** Measured footprints (width x height, in ball diameters). */
const FOOTPRINTS: Array<[StateId, number, number, number, number]> = [
  // state,       time,  width,   height,  tolerance
  ['idle', 0.5, 2.0, 2.0, 0.05],
  ['egg', 0.9, 1.653, 2.0, 0.06],
  ['hexagon', 0.9, 1.82, 2.01, 0.07],
  ['exclaim', 0.9, 0.263, 0.842, 0.03],
  ['alert', 0.8, 0.421, 0.753, 0.04],
  ['sleep', 0.6, 0.317, 0.317, 0.03],
  ['comet', 1.0, 0.258, 0.258, 0.03]
]

describe('silhouettes', () => {
  for (const [id, t, w, h, tol] of FOOTPRINTS) {
    it(`"${id}" matches the measured footprint`, () => {
      const e = new BotEngine(100, id)
      const { w: gw, h: gh } = footprint(e.sample(t).bodyPath)
      expect(Math.abs(gw - w)).toBeLessThan(tol)
      expect(Math.abs(gh - h)).toBeLessThan(tol)
    })
  }

  it('the resting ball is a circle, not an oval', () => {
    const e = new BotEngine(100, 'idle')
    const { w, h } = footprint(e.sample(0.5).bodyPath)
    expect(Math.abs(w - h)).toBeLessThan(0.03)
  })

  it('the triangle is wider than tall, pointing up', () => {
    const e = new BotEngine(100, 'play')
    const { w, h } = footprint(e.sample(0.9).bodyPath)
    expect(w).toBeGreaterThan(h)
    expect(Math.abs(w - 1.99)).toBeLessThan(0.08)
  })
})

describe('engine', () => {
  it('is a pure function of time: two reads at the same time are identical', () => {
    const a = new BotEngine(100, 'orbit')
    const b = new BotEngine(100, 'orbit')
    expect(a.sample(1.3).bodyPath).toBe(b.sample(1.3).bodyPath)
    // and re-reading an already past time gives back the same image
    const first = a.sample(0.7).bodyPath
    a.sample(2.5)
    expect(a.sample(0.7).bodyPath).toBe(first)
  })

  it('stays replayable DURING a crossfade between states', () => {
    // the trap: purging the previous state once the fade is over makes this
    // time unrecoverable, and the fade disappears on replay
    const e = new BotEngine(100, 'idle')
    e.setState('egg', 1)
    const during = e.sample(1.2).bodyPath
    e.sample(3)
    expect(e.sample(1.2).bodyPath).toBe(during)
  })

  it('does not go haywire on a time before the state change', () => {
    // before the change, there is nothing to fade: the outgoing state must show
    const e = new BotEngine(100, 'idle')
    const before = e.sample(0.5).bodyPath
    e.setState('egg', 1)
    expect(e.sample(0.5).bodyPath).toBe(before)
  })

  it('really animates: the shape changes between two times', () => {
    const e = new BotEngine(100, 'thinking')
    const paths = [0.1, 0.4, 0.8, 1.2].map((t) => e.sample(t).bodyPath)
    expect(new Set(paths).size).toBe(paths.length)
  })

  it('interpolates the silhouette during a transition, without jumping', () => {
    const e = new BotEngine(100, 'idle')
    e.setState('egg', 1)
    const widths = [1, 1.1, 1.2, 1.3, 1.4].map((t) => footprint(e.sample(t).bodyPath).w)
    // strictly decreasing: the ball shrinks toward the egg
    for (let i = 1; i < widths.length; i++) {
      expect(widths[i]!).toBeLessThan(widths[i - 1]!)
    }
    expect(widths[0]!).toBeCloseTo(2, 1)
    expect(footprint(e.sample(2).bodyPath).w).toBeCloseTo(1.65, 1)
  })

  it('never lets the body overflow the viewBox', () => {
    for (const s of STATES) {
      const e = new BotEngine(100, s.id)
      for (const t of [0.2, 0.9, 1.8, 3]) {
        const pts = anchors(e.sample(t).bodyPath)
        for (const [x, y] of pts) {
          expect(Math.abs(x)).toBeLessThan(158)
          expect(Math.abs(y)).toBeLessThan(158)
        }
      }
    }
  })
})

describe('custom shape', () => {
  const radii = (id: string) => SHAPE_BY_ID.get(id)!.radii
  const height = (e: BotEngine, t: number) => footprint(e.sample(t).bodyPath).h

  it('replaces the silhouette of resting states', () => {
    const rond = new BotEngine(100, 'idle')
    const droplet = new BotEngine(100, 'idle', radii('droplet'))
    expect(droplet.sample(1).bodyPath).not.toBe(rond.sample(1).bodyPath)
  })

  it('leaves untouched the states that draw their own shape', () => {
    for (const id of ['exclaim', 'alert', 'sleep', 'egg', 'hexagon'] as const) {
      const bare = new BotEngine(100, id)
      const dressed = new BotEngine(100, id, radii('droplet'))
      expect(dressed.sample(1).bodyPath).toBe(bare.sample(1).bodyPath)
    }
  })

  it('morphs to the new shape instead of jumping', () => {
    const e = new BotEngine(100, 'idle', radii('circle'))
    // the circle is 2.0 tall, the capsule 1.24: height is telling
    expect(height(e, 1)).toBeCloseTo(2, 1)
    e.setShape(radii('capsule'), 1)

    const steps = [1.06, 1.14, 1.26].map((t) => height(e, t))
    // strictly decreasing, and never already arrived
    for (let i = 1; i < steps.length; i++) {
      expect(steps[i]!).toBeLessThan(steps[i - 1]!)
    }
    expect(steps[0]!).toBeLessThan(2)
    expect(steps[steps.length - 1]!).toBeGreaterThan(1.24)

    // arrived after the morph duration
    expect(height(e, 1 + BotEngine.SHAPE_MORPH + 0.05)).toBeCloseTo(1.24, 1)
  })

  it('stays a pure function of time during a shape morph', () => {
    const e = new BotEngine(100, 'idle', radii('circle'))
    e.setShape(radii('capsule'), 1)
    const middle = e.sample(1.1).bodyPath
    // go past the end of the morph, then re-read the past time
    e.sample(3)
    expect(e.sample(1.1).bodyPath).toBe(middle)
  })

  it('keeps the eyes inside the silhouette on a non-circular shape', () => {
    for (const id of ['cloud', 'capsule', 'droplet', 'triangle', 'squircle'] as const) {
      const f = new BotEngine(100, 'idle', radii(id)).sample(1)
      expect(f.eyes).toHaveLength(2)
      for (const eye of f.eyes) {
        const parts = /matrix\(([^)]+)\)/.exec(eye.matrix)![1]!.split(',').map(Number)
        const ex = parts[4]!
        const ey = parts[5]!
        const edge = radiusAtAngle(radii(id), Math.atan2(ey, ex)) * 100
        // the eye center must stay well inside the outline
        expect(Math.hypot(ex, ey)).toBeLessThan(edge)
      }
    }
  })
})

describe('states', () => {
  /**
   * The sequence is the CATALOG: the 14 measured states, the ones the
   * palette offers and the board shows. Any state outside the sequence is an
   * interface transition, chosen rather than measured, so it must never appear in
   * the catalog, and staying out of it is precisely what is checked.
   */
  it('keeps the 14 catalogue states in the sequence, and nothing else', () => {
    expect(SEQUENCE).toHaveLength(14)
    expect(new Set(SEQUENCE).size).toBe(14)
    for (const id of SEQUENCE) expect(STATES.some((s) => s.id === id), id).toBe(true)
  })

  it('keeps interface transitions out of the catalog', () => {
    const outOfSequence = STATES.filter((s) => !SEQUENCE.includes(s.id)).map((s) => s.id)
    expect(outOfSequence).toEqual(['swirl'])
  })

  it('shows the face on face states, hides it on the others', () => {
    const withIt: StateId[] = ['idle', 'wink', 'wide', 'notify', 'egg', 'hexagon']
    const without: StateId[] = ['thinking', 'alert', 'exclaim', 'sleep']
    for (const id of withIt) expect(new BotEngine(100, id).sample(0.9).eyes.length).toBe(2)
    for (const id of without) expect(new BotEngine(100, id).sample(0.9).eyes.length).toBe(0)
  })

  it('cuts a notch around the notification badge', () => {
    const f = new BotEngine(100, 'notify').sample(1)
    expect(f.notif).not.toBeNull()
    expect(f.notch).not.toBeNull()
    // measured constant margin: 0.054 radius
    expect((f.notch!.r - f.notif!.r) / 100).toBeCloseTo(0.054, 2)
    // the badge sits on the circumference
    expect(Math.hypot(f.notif!.x, f.notif!.y) / 100).toBeCloseTo(1.003, 1)
  })

  it('draws the rings in front of AND behind the body', () => {
    const f = new BotEngine(100, 'orbit').sample(1.4)
    expect(f.arcs.length).toBeGreaterThan(3)
    expect(f.arcs.some((a) => a.back.length > 0)).toBe(true)
    expect(f.arcs.some((a) => a.front.length > 0)).toBe(true)
  })

  it('spirals the particles toward the center during the burst', () => {
    const e = new BotEngine(100, 'burst')
    const radius = (t: number) => {
      const d = e.sample(t).dots[0]
      return d ? Math.hypot(d.x, d.y) : 0
    }
    expect(radius(0.15)).toBeGreaterThan(radius(0.45))
    expect(radius(0.45)).toBeGreaterThan(0)
  })
})

describe('gaze following the pointer', () => {
  /** X coordinate of the inner eye, in viewBox px. */
  const eyeX = (e: BotEngine, t: number) => +/matrix\([^,]+,[^,]+,[^,]+,[^,]+,(-?[\d.]+)/
    .exec(e.sample(t).eyes[0]!.matrix)![1]!

  /** Amplitude of its displacement over a time range. */
  function amplitude(e: BotEngine, from: number, a: number) {
    const xs: number[] = []
    for (let t = from; t <= a; t += 0.1) xs.push(eyeX(e, t))
    return Math.max(...xs) - Math.min(...xs)
  }

  it('leaves the gaze alone while no target is set', () => {
    const bare = new BotEngine(100, 'idle')
    const aim = new BotEngine(100, 'idle')
    aim.setLook(null, 0)
    expect(aim.sample(1).eyes[0]!.matrix).toBe(bare.sample(1).eyes[0]!.matrix)
  })

  it('aims the gaze at the target yaw, in absolute terms', () => {
    const right = new BotEngine(100, 'idle')
    const left = new BotEngine(100, 'idle')
    right.setLook({ yaw: 45, pitch: 0, mix: 1, spin: 0, wander: 0 }, 0)
    left.setLook({ yaw: -45, pitch: 0, mix: 1, spin: 0, wander: 0 }, 0)
    const t = 1 + BotEngine.LOOK_MORPH
    expect(eyeX(right, t)).toBeGreaterThan(eyeX(left, t) + 40)
  })

  it('replaces the yaw of the pose instead of adding to it', () => {
    // This is what makes expression changes smooth: the caller does not have to
    // subtract the expression's yaw, so it does not have to know its value,
    // which, during a morph, is not yet the target one.
    // Two expressions that differ ONLY by their yaw: an eye's X coordinate also
    // depends on pitch and eye spacing, so varying them together would prove
    // nothing.
    const model = EXPRESSION_BY_ID.get('neutral')!
    const leftHanded = { ...model, gaze: { ...model.gaze, yaw: -30 } }
    const rightHanded = { ...model, gaze: { ...model.gaze, yaw: 60 } }
    const circle = SHAPE_BY_ID.get('circle')!.radii

    const a = new BotEngine(100, 'idle', circle, leftHanded)
    const b = new BotEngine(100, 'idle', circle, rightHanded)
    // without a target, the two look clearly away from each other
    expect(Math.abs(eyeX(a, 1) - eyeX(b, 1))).toBeGreaterThan(40)

    a.setLook({ yaw: -26, pitch: 0, mix: 1, spin: 0, wander: 0 }, 1)
    b.setLook({ yaw: -26, pitch: 0, mix: 1, spin: 0, wander: 0 }, 1)
    // ...and the same aimed yaw puts them exactly at the same spot
    const t = 1 + BotEngine.LOOK_MORPH
    expect(eyeX(a, t)).toBeCloseTo(eyeX(b, t), 5)
  })

  it('goes through the requested turn without changing the end point', () => {
    const direct = new BotEngine(100, 'idle')
    const turns = new BotEngine(100, 'idle')
    direct.setLook({ yaw: -26, pitch: 0, mix: 1, spin: 0, wander: 0 }, 0)
    turns.setLook({ yaw: -26, pitch: 0, mix: 1, spin: 360, wander: 0 }, 0)
    const t = 1 + BotEngine.LOOK_MORPH
    // a full turn is the same angle: the image must be pixel-identical
    expect(turns.sample(t).eyes[0]!.matrix).toBe(direct.sample(t).eyes[0]!.matrix)
    // ...whereas at half-turn the face is opposite the viewer
    const mi = new BotEngine(100, 'idle')
    mi.setLook({ yaw: -26, pitch: 0, mix: 1, spin: 180, wander: 0 }, 0)
    expect(mi.sample(t).eyes).toHaveLength(0)
  })

  it('keeps both eyes visible at extreme amplitudes', () => {
    // beyond that, the outer eye goes behind the sphere's limb and the engine
    // removes it: the stop in the avatar component must stay below
    for (const yaw of [-42, -26, -10]) {
      for (const pitch of [-3, 10, 23]) {
        const e = new BotEngine(100, 'idle')
        e.setLook({ yaw, pitch, mix: 1, spin: 0, wander: 0 }, 0)
        expect(e.sample(1).eyes, `yaw ${yaw} pitch ${pitch}`).toHaveLength(2)
      }
    }
  })

  it('turns off the automatic drift when the pointer is in control', () => {
    const free = new BotEngine(100, 'idle')
    const held = new BotEngine(100, 'idle')
    held.setLook({ yaw: REST_GAZE.yaw, pitch: 0, mix: 1, spin: 0, wander: 0 }, 0)

    // Same target as the resting gaze: whatever motion remains is therefore
    // ONLY the drift. It must have faded out, except that the body float
    // (±0.006 radius, `float`) is not affected.
    expect(amplitude(held, 1, 8)).toBeLessThan(2)
    expect(amplitude(free, 1, 8)).toBeGreaterThan(5 * amplitude(held, 1, 8))
  })

  it('returns to the gaze of the state when the target is released', () => {
    const bare = new BotEngine(100, 'idle')
    const e = new BotEngine(100, 'idle')
    e.setLook({ yaw: -20, pitch: -10, mix: 1, spin: 0, wander: 0 }, 0)
    e.sample(1)
    e.setLook(null, 1)
    // the return is gradual, then complete
    expect(eyeX(e, 1.05)).not.toBeCloseTo(eyeX(bare, 1.05), 1)
    const finished = 1 + BotEngine.LOOK_MORPH
    expect(eyeX(e, finished)).toBeCloseTo(eyeX(bare, finished), 5)
  })

  it('stays a pure function of time during the catch-up', () => {
    const e = new BotEngine(100, 'idle')
    e.setLook({ yaw: -18, pitch: -8, mix: 1, spin: 0, wander: 0 }, 1)
    const middle = e.sample(1.1).eyes[0]!.matrix
    // re-reading a past time must give back exactly the same image
    e.sample(3)
    expect(e.sample(1.1).eyes[0]!.matrix).toBe(middle)
  })

  it('leaves the drift intact on thumbnails, which never aim', () => {
    // a frozen thumbnail does not call setLook: its gaze must drift as before
    const e = new BotEngine(100, 'idle')
    expect(amplitude(e, 0, 6)).toBeGreaterThan(4)
  })
})

describe('gaze robustness', () => {
  it('rejects a non-finite target instead of remembering it', () => {
    /**
     * The engine KEEPS the last target: a `NaN` set a single time would propagate
     * to every frame and the bot would never settle again. Really happened:
     * `getBoundingClientRect` on a zero-size box gives `0 / 0` in the caller.
     */
    const healthy = new BotEngine(100, 'idle')
    const e = new BotEngine(100, 'idle')
    e.setLook({ yaw: NaN, pitch: 10, mix: 1, spin: 0, wander: 0 }, 0)
    expect(e.sample(1).eyes[0]!.matrix).toBe(healthy.sample(1).eyes[0]!.matrix)

    // and a sane target set afterwards still works
    e.setLook({ yaw: -26, pitch: 10, mix: 1, spin: 0, wander: 0 }, 1)
    expect(e.sample(1 + BotEngine.LOOK_MORPH).eyes[0]!.matrix).not.toBe(
      healthy.sample(1 + BotEngine.LOOK_MORPH).eyes[0]!.matrix
    )
  })

  it('keeps a turned head alive when no pointer controls it', () => {
    /**
     * Fixed regression: `mix` turned off the drift at the same time as it took
     * over the direction. Arriving on the view by keyboard or touch then gave a
     * completely frozen avatar, which contradicts the definition of the resting
     * state ("gaze drift and blinks").
     */
    const eyeX = (e: BotEngine, t: number) => +/matrix\([^,]+,[^,]+,[^,]+,[^,]+,(-?[\d.]+)/
      .exec(e.sample(t).eyes[0]!.matrix)![1]!
    const amplitude = (e: BotEngine) => {
      const xs: number[] = []
      for (let t = 1; t <= 8; t += 0.1) xs.push(eyeX(e, t))
      return Math.max(...xs) - Math.min(...xs)
    }

    const withoutPointer = new BotEngine(100, 'idle')
    withoutPointer.setLook({ yaw: -26, pitch: 10, mix: 1, spin: 0, wander: 1 }, 0)
    const withPointer = new BotEngine(100, 'idle')
    withPointer.setLook({ yaw: -26, pitch: 10, mix: 1, spin: 0, wander: 0 }, 0)

    // the head is turned in both cases...
    expect(eyeX(withoutPointer, 1)).toBeLessThan(0)
    expect(eyeX(withPointer, 1)).toBeLessThan(0)
    // ...but only the one nobody controls keeps drifting
    expect(amplitude(withoutPointer)).toBeGreaterThan(5 * amplitude(withPointer))
  })
})

/**
 * `reset`: restart on a state WITHOUT history.
 *
 * It is one more public method on what is meant to become an API, so it deserves its own
 * direct test and not just the indirect coverage of the offscreen player.
 */
describe('reset', () => {
  it('forgets the previous state, where setState keeps it to blend', () => {
    const withFade = new BotEngine(100, 'idle')
    withFade.setState('egg', 0)
    const reset = new BotEngine(100, 'idle')
    reset.reset('egg', 0)

    // at the start of the morph, one still blends in the resting state, the other is
    // already the egg
    expect(withFade.sample(0).bodyPath).not.toBe(reset.sample(0).bodyPath)
    // and the egg alone is indeed what a fresh engine on `egg` renders
    expect(reset.sample(0).bodyPath).toBe(new BotEngine(100, 'egg').sample(0).bodyPath)
  })

  /*
   * Compare at an EQUAL absolute time, not a pose timed at 0 against one timed at 5: the
   * resting drift depends on absolute time, so two different times never give the same
   * path, even on a state with a fixed pose. The comparison would say nothing.
   */
  it('dates the state where it is told to', () => {
    const tot = new BotEngine(100, 'idle')
    tot.reset('alert', 0)
    const late = new BotEngine(100, 'idle')
    late.reset('alert', 5)
    // the "!" is crossing: at the same absolute time, one is at 5 s, the other at the start
    expect(tot.sample(5).bodyPath).not.toBe(late.sample(5).bodyPath)
    expect(late.state).toBe('alert')
  })

  it('leaves sample a pure function of time', () => {
    const e = new BotEngine(100, 'idle')
    e.reset('orbit', 0)
    const tot = e.sample(0.3).bodyPath
    e.sample(9)
    expect(e.sample(0.3).bodyPath).toBe(tot)
  })
})

/**
 * A state change arriving DURING a fade.
 *
 * The engine keeps only one slot of history, so the origin of the new blend became the
 * FULL pose of the state being left, instead of the partially blended image that was on
 * screen: a jump. It now blends from the composite pose frozen at the moment of the
 * change.
 *
 * Measured: an eye's displacement over the two frames following a change. A SPACED-OUT
 * change produces 10 to 14 px, and that is intended: the measured `easeOutQuint`
 * starts steep. What was not intended was the 26 to 43 px of a change in mid-fade.
 */
describe('state change during a crossfade', () => {
  const IMAGE = 1 / 60

  /** Max displacement of an eye over the two frames following `at`. */
  function jumpAfter(changes: Array<[StateId, number]>, at: number) {
    const e = new BotEngine(100, 'idle')
    const distances: Array<{ t: number; d: number[] }> = []
    let i = 0
    for (let t = 0; t <= at + 4 * IMAGE; t += IMAGE) {
      while (i < changes.length && changes[i]![1] <= t + 1e-9) {
        e.setState(changes[i]![0], changes[i]![1])
        i++
      }
      distances.push({
        t,
        d: e.sample(t).eyes.map((y) => {
          const n = y.matrix.match(/-?\d+\.?\d*/g)!.map(Number)
          return Math.hypot(n[4]!, n[5]!)
        })
      })
    }
    let worst = 0
    for (let k = 1; k < distances.length; k++) {
      const a = distances[k - 1]!
      const b = distances[k]!
      if (a.d.length !== b.d.length || b.t <= at || b.t > at + 2.5 * IMAGE) continue
      worst = Math.max(worst, ...a.d.map((v, j) => Math.abs(v - b.d[j]!)))
    }
    return worst
  }

  /** Reference: the same change, but spaced out. This is the normal motion. */
  const NORMAL = 14

  it('jumps no more than a spaced-out change', () => {
    const space = jumpAfter([['wide', 0.5], ['idle', 2]], 2)
    expect(space).toBeLessThan(NORMAL)

    // 100 ms after the first, so in the middle of the 0.55 s fade
    expect(jumpAfter([['wide', 0.5], ['idle', 0.6]], 0.6)).toBeLessThanOrEqual(space)
  })

  it('holds up on chained changes', () => {
    const frames: Array<[StateId, number]> = [
      ['wide', 0.5],
      ['idle', 0.55],
      ['egg', 0.6],
      ['orbit', 0.65],
      ['notify', 0.7]
    ]
    for (const [, at] of frames.slice(1)) {
      expect(jumpAfter(frames, at), `change at ${at}s`).toBeLessThan(NORMAL)
    }
  })

  /**
   * And SPACED-OUT playback does not change: a montage's blocks last at least as long as
   * the longest fade, so nothing is ever frozen there. Checked on the full sequence, frame
   * by frame: this is what protects the measured animations.
   */
  it('changes nothing for a spaced-out read', () => {
    const frames: Array<[StateId, number]> = [
      ['thinking', 1],
      ['wink', 2],
      ['alert', 3]
    ]
    const withHistory = new BotEngine(100, 'idle')
    let i = 0
    const images: string[] = []
    for (let t = 0; t < 4; t += IMAGE) {
      while (i < frames.length && frames[i]![1] <= t + 1e-9) {
        withHistory.setState(frames[i]![0], frames[i]![1])
        i++
      }
      images.push(withHistory.sample(t).bodyPath)
    }
    // no empty frame, and the "!" of `alert` still moves while it fades
    expect(images.every((p) => p.length > 0)).toBe(true)
    expect(new Set(images.slice(-12)).size).toBeGreaterThan(1)
  })
})
